### ISSUE TITLE
Error when rating submitter

### ISSUE THREAD

**Issue by john-light** [Bounties-Network/bounties.network#15]
Attempted to leave rating and review, received error:

> Something went wrong. Please try again later.

**Comment by villanuevawill** [comment]
@john-light we experienced a momentary spike in traffic - I'm not sure if that was the issue... What browser/os are you on?

**Comment by villanuevawill** [comment]
Are you able to retry?

**Comment by john-light** [comment]
Yeah it works now! Thanks
