### ISSUE TITLE
Submitted a bounty but it doesn't show up in the dashboard

### ISSUE THREAD

**Issue by James-Sangalli** [Bounties-Network/bounties.network#19]
Successfully took my 500 DAI for the bounty and sent it to the contract here: https://etherscan.io/tx/0xd97d8974b75f8d46c1f39e970fe8ad5d5ab18875e510e888d0f1c583f989f0be

But I cannot see my bounty at all and the website asks me to submit it again, thereby asking for another contribution of 500 DAI...

Please fix this ASAP as we need it for ETHBerlin. 

<img width="785" alt="Screen Shot 2019-08-09 at 11 04 31 am" src="https://user-images.githubusercontent.com/16630514/62746952-7fe33180-ba95-11e9-850c-0ac43b37b00e.png">

**Comment by mbeylin** [comment]
James, thank you for bringing this up. I've taken a look and it seems like our backend funk'd out when trying to query IPFS-- my apologies on its behalf.

I've gone ahead and manually added your bounty to our caching layer so everything should function as usual https://explorer.bounties.network/bounty/3257. Let me know if you experience any odd behaviour; the best bet would be to de-activate the bounty if you _do_ notice anything funny and simply re-create it anew (or just comment here and I'd be happy to help).

In the meantime, I'll take a look at why our IPFS node keeps going down. Thank you for bringing this to my attention!

**Comment by James-Sangalli** [comment]
Working now, thanks for your help!
