### ISSUE TITLE
Mist browser 0.10 compatibility

### ISSUE THREAD

**Issue by michaelgracie** [Bounties-Network/bounties.network#6]
Hangs using Mist browser 0.10.  Running full node on Rinkeby network, fast connection, plenty of peers, no sync issues, positive ether balance.  Already informed testing has been done with Toshi, TrustWallet and MetaMask.  Screenshots attached before & after authorization.
![screenshot1](https://user-images.githubusercontent.com/8391046/40185379-b6f238bc-59af-11e8-9ff7-22ccfa681b99.jpeg)
![screenshot2](https://user-images.githubusercontent.com/8391046/40185380-b72bccc6-59af-11e8-8ff9-e0aaddf765f0.jpeg)

**Comment by mbeylin** [comment]
After a bit of investigation, I've realized that this is the error message which users are prompted with when they haven't clicked "connect" using mist. Would it be better for us to simply change the error message to say ` No accounts detected, please connect or unlock an Ethereum account to use the Bounties Network`?

**Comment by michaelgracie** [comment]
@mbeylin That certainly would prompt the user a bit more intuitively.  However, I am not sure it solves the underlying problem, which as shown in the second screenshot is that even after authorizing an account using Mist the page doesn't recognize it.  Note that I tried this on the colorado.bounties.network page, and it shows the same "trying to connect" icon and "no account" message without showing the bounties; if I view the page in a generic browser the list of bounties shows, but obviously nothing can be done with them.

**Comment by michaelgracie** [comment]
This seems to be working now.
